import { mountainById } from "./nanshan";

export type AtlasRing = "center" | "zhong" | "shan" | "hai" | "hainei" | "haiwai" | "dahuang";
export type CompassDir = "center" | "n" | "e" | "s" | "w";

export interface AtlasLocus {
  id: string;
  name: string;
  jing: string;
  ring: AtlasRing;
  dir: CompassDir;
  /** Compass degrees clockwise from north. */
  deg: number;
  /** 0 = center, 1 = map rim. */
  r: number;
  walkable: boolean;
  worldX?: number;
  worldZ?: number;
  quote: string;
  modern: string;
  mythNote?: string;
  lockedHint?: string;
  /** Always draw the name (myth anchors and walkable 南山). */
  featured?: boolean;
}

export interface PlacedLocus extends AtlasLocus {
  mx: number;
  my: number;
}

export const RING_RADIUS: Record<AtlasRing, number> = {
  center: 0,
  zhong: 0.155,
  shan: 0.3,
  hai: 0.415,
  hainei: 0.54,
  haiwai: 0.69,
  dahuang: 0.855,
};

export const RING_LABELS: { ring: AtlasRing; name: string; r: number }[] = [
  { ring: "zhong", name: "中山經", r: 0.155 },
  { ring: "shan", name: "山經", r: 0.3 },
  { ring: "hai", name: "海", r: 0.415 },
  { ring: "hainei", name: "海內", r: 0.54 },
  { ring: "haiwai", name: "海外", r: 0.69 },
  { ring: "dahuang", name: "大荒", r: 0.855 },
];

export const SEA_LABELS: { name: string; deg: number; r: number }[] = [
  { name: "北海", deg: 0, r: 0.415 },
  { name: "東海", deg: 90, r: 0.415 },
  { name: "南海", deg: 180, r: 0.415 },
  { name: "西海", deg: 270, r: 0.415 },
];

export const JING_LABELS: { name: string; deg: number; r: number }[] = [
  { name: "北山經", deg: 12, r: 0.3 },
  { name: "東山經", deg: 90, r: 0.3 },
  { name: "南山經", deg: 180, r: 0.3 },
  { name: "西山經", deg: 270, r: 0.3 },
];

/** Canvas / atlas space: north is −Y, east is +X, coords in −1…1. */
export function polarToMap(r: number, deg: number): { mx: number; my: number } {
  const rad = (deg * Math.PI) / 180;
  return { mx: Math.sin(rad) * r, my: -Math.cos(rad) * r };
}

const LOCI: AtlasLocus[] = [
  {
    id: "pangu",
    name: "盤古 · 渾沌",
    jing: "天地未形",
    ring: "center",
    dir: "center",
    deg: 0,
    r: 0,
    walkable: false,
    quote: "天地渾沌如雞子。盤古生在其中。萬八千歲。天地開辟。",
    modern: "盤古開天地，化身為四極五嶽。",
    mythNote: "不出《山海經》。出《三五曆紀》《述異記》。置於地圖中央渾沌，不作經山。",
    lockedHint: "開天闢地，尚無九州可履。",
    featured: true,
  },

  {
    id: "youxi",
    name: "游戲之山",
    jing: "中山經",
    ring: "zhong",
    dir: "s",
    deg: 150,
    r: 0.15,
    walkable: false,
    quote: "又東南三十里，曰游戲之山，多杻橿穀，多玉、多封石。",
    modern: "中山近畿，杻橿穀木。",
    lockedHint: "尚未開通。",
  },
  {
    id: "ying",
    name: "嬰山",
    jing: "中山經",
    ring: "zhong",
    dir: "e",
    deg: 88,
    r: 0.14,
    walkable: false,
    quote: "又東四十里，曰嬰山，其下多青䨼，其上多金玉。",
    modern: "下多青雘，上多金玉。",
    lockedHint: "尚未開通。",
  },
  {
    id: "ji-zhong",
    name: "鷄山",
    jing: "中山經",
    ring: "zhong",
    dir: "e",
    deg: 118,
    r: 0.165,
    walkable: false,
    quote: "又東南四十里，曰鷄山，其上多美梓，多桑，其草多韭。",
    modern: "中山鷄山，美梓與桑。與南山經鷄山同名異地。",
    lockedHint: "尚未開通。",
  },
  {
    id: "yongshi",
    name: "勇石之山",
    jing: "中山經",
    ring: "zhong",
    dir: "w",
    deg: 238,
    r: 0.15,
    walkable: false,
    quote: "又西南二十里，曰勇石之山，無草木，多白金，多水。",
    modern: "無草木，多白金。",
    lockedHint: "尚未開通。",
  },
  {
    id: "xiong",
    name: "熊山",
    jing: "中山經",
    ring: "zhong",
    dir: "n",
    deg: 38,
    r: 0.16,
    walkable: false,
    quote: "又東一百五十里，曰熊山。有穴焉，熊之穴，恒出神人。",
    modern: "熊穴夏啟冬閉，冬啟則有兵。",
    lockedHint: "尚未開通。",
  },

  {
    id: "zhaoyao",
    name: "招搖之山",
    jing: "南山經",
    ring: "shan",
    dir: "s",
    deg: 220,
    r: 0.3,
    walkable: true,
    worldX: mountainById("zhaoyao")!.padX,
    worldZ: mountainById("zhaoyao")!.padZ,
    quote: "其首曰招搖之山，臨於西海之上，多桂，多金玉。有草焉……名曰祝餘。有木焉……名曰迷穀。有獸焉……名曰狌狌。",
    modern: "南山首山，西臨大海。迷穀、祝餘、狌狌在此。",
    featured: true,
  },
  {
    id: "yuanyi",
    name: "猨翼之山",
    jing: "南山經",
    ring: "shan",
    dir: "s",
    deg: 200,
    r: 0.3,
    walkable: true,
    worldX: mountainById("yuanyi")!.padX,
    worldZ: mountainById("yuanyi")!.padZ,
    quote: "又東三百八十里，曰猨翼之山，其中多怪獸，水多怪魚……多怪木，不可以上。",
    modern: "怪木怪蛇，山霧濃重。",
    featured: true,
  },
  {
    id: "qingqiu",
    name: "青丘之山",
    jing: "南山經",
    ring: "shan",
    dir: "s",
    deg: 180,
    r: 0.3,
    walkable: true,
    worldX: mountainById("qingqiu")!.padX,
    worldZ: mountainById("qingqiu")!.padZ,
    quote: "又東三百里，曰青丘之山……有獸焉，其狀如狐而九尾，其音如嬰兒，能食人，食者不蠱。",
    modern: "九尾狐與灌灌鳥。",
    featured: true,
  },
  {
    id: "danxue",
    name: "丹穴之山",
    jing: "南山經",
    ring: "shan",
    dir: "s",
    deg: 162,
    r: 0.3,
    walkable: true,
    worldX: mountainById("danxue")!.padX,
    worldZ: mountainById("danxue")!.padZ,
    quote: "又東五百里，曰丹穴之山……有鳥焉，其狀如雞，五采而文，名曰鳳皇。",
    modern: "金玉之山，丹水南注。鳳皇見則天下安寧。",
    featured: true,
  },
  {
    id: "ji-nanshan",
    name: "鷄山",
    jing: "南山經",
    ring: "shan",
    dir: "s",
    deg: 145,
    r: 0.3,
    walkable: true,
    worldX: mountainById("ji-nanshan")!.padX,
    worldZ: mountainById("ji-nanshan")!.padZ,
    quote: "又東五百里，曰鷄山，其上多金，其下多丹雘。黑水出焉，而南流注于海。",
    modern: "上金下丹雘，黑水南流。",
    featured: true,
  },

  {
    id: "nuchuang",
    name: "女床之山",
    jing: "西山經",
    ring: "shan",
    dir: "w",
    deg: 270,
    r: 0.245,
    walkable: false,
    quote: "西南三百里，曰女床之山……有鳥焉，其狀如翟而五彩文，名曰鸞鳥。",
    modern: "西山內帶。鸞鳥見則天下安寧。",
    lockedHint: "尚未開通。",
  },
  {
    id: "kunlun-xishan",
    name: "崑崙之丘",
    jing: "西山經",
    ring: "shan",
    dir: "w",
    deg: 270,
    r: 0.29,
    walkable: false,
    quote: "西南四百里，曰崑崙之丘，是實惟帝之下都，神陸吾司之……有木焉……名曰沙棠，可以禦水，食之使人不溺。",
    modern: "陸吾守帝之下都。沙棠在此，與海內、大荒崑崙同名異層。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "yushan",
    name: "玉山",
    jing: "西山經",
    ring: "shan",
    dir: "w",
    deg: 270,
    r: 0.325,
    walkable: false,
    quote: "又西三百五十里，曰玉山，是西王母所居也。西王母其狀如人，豹尾虎齒而善嘯，蓬髮戴勝。",
    modern: "西王母所居。羿請不死之藥於此。",
    mythNote: "嫦娥不出《山海經》（《淮南子》）。奔月事掛於西王母之玉山。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "tianshan",
    name: "天山",
    jing: "西山經",
    ring: "shan",
    dir: "w",
    deg: 278,
    r: 0.35,
    walkable: false,
    quote: "又西三百五十里，曰天山……有神焉，其狀如黃囊……渾敦無面目，是識歌舞，實惟帝江也。",
    modern: "帝江居此，渾敦無面目。",
    lockedHint: "尚未開通。",
  },

  {
    id: "fajiu",
    name: "發鳩之山",
    jing: "北山經",
    ring: "shan",
    dir: "n",
    deg: 348,
    r: 0.3,
    walkable: false,
    quote: "又北二百里，曰發鳩之山，其上多柘木。有鳥焉……名曰精衛……常銜西山之木石，以堙於東海。",
    modern: "炎帝少女女娃溺於東海，化為精衛。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "kuang",
    name: "狂山",
    jing: "北山經",
    ring: "shan",
    dir: "n",
    deg: 6,
    r: 0.3,
    walkable: false,
    quote: "又北三百八十里，曰狂山，無草木。是山也，冬夏有雪。",
    modern: "冬夏有雪。",
    lockedHint: "尚未開通。",
  },
  {
    id: "gouwu",
    name: "鉤吾之山",
    jing: "北山經",
    ring: "shan",
    dir: "n",
    deg: 22,
    r: 0.3,
    walkable: false,
    quote: "又北三百五十里，曰鉤吾之山……有獸焉……名曰狍鴞，是食人。",
    modern: "羊身人面，目在腋下。",
    lockedHint: "尚未開通。",
  },
  {
    id: "xuanyuan",
    name: "軒轅之山",
    jing: "北山經",
    ring: "shan",
    dir: "n",
    deg: 38,
    r: 0.3,
    walkable: false,
    quote: "又東北二百里，曰軒轅之山……有鳥焉，其狀如梟而白首，其名曰黃鳥，食之不妒。",
    modern: "多銅，下多竹。",
    lockedHint: "尚未開通。",
  },

  {
    id: "beihao",
    name: "北號之山",
    jing: "東山經",
    ring: "shan",
    dir: "e",
    deg: 58,
    r: 0.3,
    walkable: false,
    quote: "東次四經之首，曰北號之山，臨于北海。",
    modern: "東山臨北海。猲狙、鬿雀食人。",
    lockedHint: "尚未開通。",
  },
  {
    id: "dongshi",
    name: "東始之山",
    jing: "東山經",
    ring: "shan",
    dir: "e",
    deg: 75,
    r: 0.3,
    walkable: false,
    quote: "又南三百二十里，曰東始之山，上多蒼玉。有木焉……其名曰芑，可以服馬。",
    modern: "東山由北而南。",
    lockedHint: "尚未開通。",
  },
  {
    id: "zitong",
    name: "子桐之山",
    jing: "東山經",
    ring: "shan",
    dir: "e",
    deg: 90,
    r: 0.3,
    walkable: false,
    quote: "又東南二百里，曰子桐之山。子桐之水出焉……其中多䱻魚……見則天下大旱。",
    modern: "魚而鳥翼，出入有光。",
    lockedHint: "尚未開通。",
  },
  {
    id: "chai",
    name: "豺山",
    jing: "東山經",
    ring: "shan",
    dir: "e",
    deg: 108,
    r: 0.3,
    walkable: false,
    quote: "又南三百里，曰豺山，其上無草木，其下多水……有獸焉，其狀如夸父而彘毛，見則天下大水。",
    modern: "無草木，下多水。",
    lockedHint: "尚未開通。",
  },
  {
    id: "fuli",
    name: "鳧麗之山",
    jing: "東山經",
    ring: "shan",
    dir: "e",
    deg: 122,
    r: 0.3,
    walkable: false,
    quote: "又南五百里，曰鳧麗之山……有獸焉，其狀如狐，而九尾、九首、虎爪，名曰蠪姪，是食人。",
    modern: "九尾九首之蠪姪。",
    lockedHint: "尚未開通。",
  },

  {
    id: "kunlun-xu",
    name: "崑崙之墟",
    jing: "海內西經",
    ring: "hainei",
    dir: "w",
    deg: 258,
    r: 0.54,
    walkable: false,
    quote: "海內崑崙之墟，在西北，帝之下都……門有開明獸守之……非仁羿莫能上岡之巖。",
    modern: "海內層崑崙。仁羿能上岡，非后羿專山。",
    mythNote: "《山海經》無后羿之山。羿見於此墟「非仁羿莫能上岡之巖」，賜弓在海內經（本教材未收）。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "kaiming",
    name: "開明獸",
    jing: "海內西經",
    ring: "hainei",
    dir: "w",
    deg: 248,
    r: 0.54,
    walkable: false,
    quote: "開明獸身大類虎而九首，皆人面，東嚮立崑崙上。",
    modern: "九首人面，守崑崙南。",
    lockedHint: "尚未開通。",
  },
  {
    id: "kaiming-bei",
    name: "開明北",
    jing: "海內西經",
    ring: "hainei",
    dir: "w",
    deg: 252,
    r: 0.505,
    walkable: false,
    quote: "開明北有視肉、珠樹、文玉樹、玕琪樹、不死樹。",
    modern: "不死樹與鳳凰鸞鳥。",
    lockedHint: "尚未開通。",
  },
  {
    id: "sanqing-hainei",
    name: "三青鳥",
    jing: "海內西經",
    ring: "hainei",
    dir: "w",
    deg: 278,
    r: 0.54,
    walkable: false,
    quote: "西王母梯几而戴勝。其南有三青鳥，為西王母取食。",
    modern: "為西王母取食。大荒西經另有三青鳥。",
    lockedHint: "尚未開通。",
  },
  {
    id: "cangwu",
    name: "蒼梧之山",
    jing: "海內南經",
    ring: "hainei",
    dir: "s",
    deg: 180,
    r: 0.54,
    walkable: false,
    quote: "蒼梧之山，帝舜葬于陽，帝丹朱葬于陰。",
    modern: "舜葬之山。",
    lockedHint: "尚未開通。",
  },
  {
    id: "xingxing-hainei",
    name: "狌狌",
    jing: "海內南經",
    ring: "hainei",
    dir: "s",
    deg: 168,
    r: 0.54,
    walkable: false,
    quote: "狌狌知人名，其為獸如豕而人面，在舜葬西。",
    modern: "與南山招搖之狌狌同名，在蒼梧之西。",
    lockedHint: "尚未開通。",
  },
  {
    id: "si",
    name: "兕",
    jing: "海內南經",
    ring: "hainei",
    dir: "s",
    deg: 192,
    r: 0.54,
    walkable: false,
    quote: "兕在舜葬東，湘水南，其狀如牛，蒼黑，一角。",
    modern: "蒼梧之東。",
    lockedHint: "尚未開通。",
  },
  {
    id: "qiongqi",
    name: "窮奇",
    jing: "海內北經",
    ring: "hainei",
    dir: "n",
    deg: 0,
    r: 0.54,
    walkable: false,
    quote: "窮奇狀如虎，有翼，食人從首始，所食被髮，在蜪犬北。",
    modern: "虎而有翼。",
    lockedHint: "尚未開通。",
  },
  {
    id: "youdu",
    name: "幽都之山",
    jing: "海內經",
    ring: "hainei",
    dir: "n",
    deg: 18,
    r: 0.54,
    walkable: false,
    quote: "北海之內，有山，名曰幽都之山，黑水出焉。",
    modern: "北海之內，玄鳥玄蛇玄豹。",
    lockedHint: "尚未開通。",
  },
  {
    id: "gunyu",
    name: "鯀禹治水",
    jing: "海內經",
    ring: "hainei",
    dir: "s",
    deg: 210,
    r: 0.52,
    walkable: false,
    quote: "洪水滔天。鯀竊帝之息壤以堙洪水……鯀復生禹。帝乃命禹卒布土以定九州。",
    modern: "祝融殺鯀于羽郊。禹定九州。",
    lockedHint: "尚未開通。",
  },

  {
    id: "xingtian",
    name: "刑天",
    jing: "海外西經",
    ring: "haiwai",
    dir: "w",
    deg: 248,
    r: 0.69,
    walkable: false,
    quote: "刑天與帝爭神，帝斷其首，葬之常羊之山，乃以乳為目，以臍為口，操干戚以舞。",
    modern: "首葬常羊之山。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "wuxian",
    name: "巫咸國",
    jing: "海外西經",
    ring: "haiwai",
    dir: "w",
    deg: 270,
    r: 0.69,
    walkable: false,
    quote: "巫咸國在女丑北，右手操青蛇，左手操赤蛇。在登葆山，群巫所從上下也。",
    modern: "登葆山，群巫升降。",
    lockedHint: "尚未開通。",
  },
  {
    id: "nuzi",
    name: "女子國",
    jing: "海外西經",
    ring: "haiwai",
    dir: "w",
    deg: 288,
    r: 0.69,
    walkable: false,
    quote: "女子國在巫咸北，兩女子居，水周之。",
    modern: "水周其國。",
    lockedHint: "尚未開通。",
  },
  {
    id: "kuafu",
    name: "夸父",
    jing: "海外北經",
    ring: "haiwai",
    dir: "n",
    deg: 0,
    r: 0.69,
    walkable: false,
    quote: "夸父與日逐走，入日。渴欲得飲，飲於河、渭……未至，道渴而死。棄其杖，化為鄧林。",
    modern: "逐日渴死。大荒北經成都載天亦記夸父。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "zhulong",
    name: "燭龍",
    jing: "海外北經",
    ring: "haiwai",
    dir: "n",
    deg: 22,
    r: 0.69,
    walkable: false,
    quote: "鍾山之神，名曰燭陰，視為晝，瞑為夜，吹為冬，呼為夏……人面蛇身，赤色，居鍾山下。",
    modern: "鍾山之神燭陰。",
    lockedHint: "尚未開通。",
  },
  {
    id: "zhurong",
    name: "祝融",
    jing: "海外南經",
    ring: "haiwai",
    dir: "s",
    deg: 180,
    r: 0.69,
    walkable: false,
    quote: "南方祝融，獸身人面，乘兩龍。",
    modern: "南方火神。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "biyi",
    name: "比翼鳥",
    jing: "海外南經",
    ring: "haiwai",
    dir: "s",
    deg: 164,
    r: 0.69,
    walkable: false,
    quote: "比翼鳥在其東，其為鳥青、赤，兩鳥比翼。",
    modern: "青赤比翼。",
    lockedHint: "尚未開通。",
  },
  {
    id: "yumin",
    name: "羽民國",
    jing: "海外南經",
    ring: "haiwai",
    dir: "s",
    deg: 152,
    r: 0.69,
    walkable: false,
    quote: "羽民國在其東南，其為人長頭，身生羽。",
    modern: "人而身羽。",
    lockedHint: "尚未開通。",
  },
  {
    id: "bifang",
    name: "畢方鳥",
    jing: "海外南經",
    ring: "haiwai",
    dir: "s",
    deg: 192,
    r: 0.69,
    walkable: false,
    quote: "畢方鳥在其東，青水西，其為鳥人面一腳。",
    modern: "人面一腳。",
    lockedHint: "尚未開通。",
  },
  {
    id: "zhushu",
    name: "株樹",
    jing: "海外南經",
    ring: "haiwai",
    dir: "s",
    deg: 204,
    r: 0.69,
    walkable: false,
    quote: "株樹在厭火北，生赤水上，其為樹如柏，葉皆為珠。",
    modern: "如柏而葉為珠。",
    lockedHint: "尚未開通。",
  },
  {
    id: "heichi",
    name: "黑齒國",
    jing: "海外東經",
    ring: "haiwai",
    dir: "e",
    deg: 72,
    r: 0.69,
    walkable: false,
    quote: "黑齒國在其北，為人黑齒，食稻啖蛇，一赤一青，在其旁。",
    modern: "扶桑之南鄰。",
    lockedHint: "尚未開通。",
  },
  {
    id: "fusang",
    name: "扶桑",
    jing: "海外東經",
    ring: "haiwai",
    dir: "e",
    deg: 90,
    r: 0.69,
    walkable: false,
    quote: "湯谷上有扶桑，十日所浴，在黑齒北。居水中，有大木，九日居下枝，一日居上枝。",
    modern: "十日所浴。后羿射日之事掛於此。",
    mythNote: "《山海經》無后羿之山。射日出《淮南子》。十日在湯谷扶桑；羿上岡見海內西經崑崙之墟。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "junzi",
    name: "君子國",
    jing: "海外東經",
    ring: "haiwai",
    dir: "e",
    deg: 108,
    r: 0.69,
    walkable: false,
    quote: "君子國在其北，衣冠帶劍，食獸，使二大虎在旁，其人好讓不爭。",
    modern: "好讓不爭。",
    lockedHint: "尚未開通。",
  },

  {
    id: "buzhou",
    name: "不周之山",
    jing: "大荒西經",
    ring: "dahuang",
    dir: "w",
    deg: 312,
    r: 0.855,
    walkable: false,
    quote: "西北海之外，大荒之隅，有山而不合，名曰不周。",
    modern: "共工怒觸之處。女媧補天之事掛於此柱。",
    mythNote: "女媧補天不出《山海經》（《淮南子》）。經中女媧之腸在大荒西栗廣之野，本教材未收，故與共工同置不周。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "buzhou-fuzi",
    name: "不周負子",
    jing: "大荒西經",
    ring: "dahuang",
    dir: "w",
    deg: 322,
    r: 0.855,
    walkable: false,
    quote: "西北海之外，大荒之隅，有山而不合，名曰不周負子……有禹攻共工國山。",
    modern: "兩黃獸守之。禹攻共工國山在其側。",
    lockedHint: "尚未開通。",
  },
  {
    id: "kunlun-dahuang",
    name: "崑崙之丘",
    jing: "大荒西經",
    ring: "dahuang",
    dir: "w",
    deg: 258,
    r: 0.855,
    walkable: false,
    quote: "西海之南，流沙之濱……有大山，名曰崑崙之丘……有人，戴勝，虎齒，有豹尾，穴處，名曰西王母。",
    modern: "大荒層崑崙。西王母穴處。此山萬物盡有。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "lingshan",
    name: "靈山",
    jing: "大荒西經",
    ring: "dahuang",
    dir: "w",
    deg: 278,
    r: 0.855,
    walkable: false,
    quote: "有靈山，巫咸、巫即、巫肦、巫彭、巫姑、巫真、巫禮、巫抵、巫謝、巫羅十巫，從此升降，百藥爰在。",
    modern: "十巫升降，百藥所在。",
    lockedHint: "尚未開通。",
  },
  {
    id: "sanqing-dahuang",
    name: "三青鳥",
    jing: "大荒西經",
    ring: "dahuang",
    dir: "w",
    deg: 288,
    r: 0.855,
    walkable: false,
    quote: "有三青鳥，赤首黑目，一名曰大鵹，一名少鵹，一名曰青鳥。",
    modern: "赤首黑目。海內西經亦有三青鳥。",
    lockedHint: "尚未開通。",
  },
  {
    id: "wucai",
    name: "五彩鳥",
    jing: "大荒西經",
    ring: "dahuang",
    dir: "w",
    deg: 242,
    r: 0.855,
    walkable: false,
    quote: "有五彩鳥三名：一曰皇鳥，一曰鸞鳥，一曰鳳鳥。",
    modern: "皇、鸞、鳳。",
    lockedHint: "尚未開通。",
  },
  {
    id: "changxi",
    name: "常羲",
    jing: "大荒西經",
    ring: "dahuang",
    dir: "w",
    deg: 230,
    r: 0.855,
    walkable: false,
    quote: "有女子方浴月。帝俊妻常羲，生月十有二，此始浴之。",
    modern: "浴月之處。嫦娥奔月掛於西王母與常羲。",
    mythNote: "嫦娥不出《山海經》。月神在經為常羲。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "gonggong-tai",
    name: "共工之臺",
    jing: "大荒北經",
    ring: "dahuang",
    dir: "n",
    deg: 0,
    r: 0.855,
    walkable: false,
    quote: "有係昆之山者，有共工之臺，射者不敢北嚮。",
    modern: "黃帝女魃、蚩尤之戰亦記於此篇。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "chengdu",
    name: "成都載天",
    jing: "大荒北經",
    ring: "dahuang",
    dir: "n",
    deg: 22,
    r: 0.855,
    walkable: false,
    quote: "大荒之中，有山名曰成都載天。有人珥兩黃蛇，把兩黃蛇，名曰夸父。",
    modern: "夸父追日，死于此。應龍又殺夸父。",
    lockedHint: "尚未開通。",
  },
  {
    id: "xihe",
    name: "羲和",
    jing: "大荒南經",
    ring: "dahuang",
    dir: "s",
    deg: 155,
    r: 0.855,
    walkable: false,
    quote: "東南海之外，甘水之間，有羲和之國。有女子名曰羲和，方浴日於甘淵。羲和者，帝俊之妻，是生十日。",
    modern: "生十日，浴日於甘淵。與扶桑十日相應。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "junren",
    name: "菌人",
    jing: "大荒南經",
    ring: "dahuang",
    dir: "s",
    deg: 188,
    r: 0.855,
    walkable: false,
    quote: "有小人名曰菌人。",
    modern: "大荒南之小人。",
    lockedHint: "尚未開通。",
  },
  {
    id: "kui",
    name: "流波山 · 夔",
    jing: "大荒東經",
    ring: "dahuang",
    dir: "e",
    deg: 78,
    r: 0.855,
    walkable: false,
    quote: "東海中有流波山，入海七千里。其上有獸……其名曰夔。黃帝得之，以其皮為鼓。",
    modern: "一足蒼身，出沒則風雨。",
    lockedHint: "尚未開通。",
    featured: true,
  },
  {
    id: "nieyao",
    name: "孽搖頵羝",
    jing: "大荒東經",
    ring: "dahuang",
    dir: "e",
    deg: 98,
    r: 0.855,
    walkable: false,
    quote: "大荒之中，有山名曰孽搖頵羝，上有扶木……湯谷上有扶木。一日方至，一日方出，皆載於烏。",
    modern: "湯谷扶木，十日所出。與海外東經扶桑同叢。",
    lockedHint: "尚未開通。",
  },
];

export const ATLAS: PlacedLocus[] = LOCI.map((locus) => {
  const { mx, my } = polarToMap(locus.r, locus.deg);
  return { ...locus, mx, my };
});

export const WALKABLE = ATLAS.filter((l) => l.walkable);

const ZHAOYAO = ATLAS.find((l) => l.id === "zhaoyao")!;
const JISHAN = ATLAS.find((l) => l.id === "ji-nanshan")!;

/** Project the 南山 region onto the south 山經 arc (招搖 west → 鷄山 east). */
export function nanshanToAtlas(x: number, z: number): { mx: number; my: number } {
  const x0 = ZHAOYAO.worldX ?? 0;
  const x1 = JISHAN.worldX ?? 1;
  const t = Math.min(1, Math.max(0, (x - x0) / (x1 - x0 || 1)));
  const deg = ZHAOYAO.deg + t * (JISHAN.deg - ZHAOYAO.deg);
  const r = RING_RADIUS.shan + (z / 280) * 0.03;
  return polarToMap(r, deg);
}

export function locusById(id: string): PlacedLocus | undefined {
  return ATLAS.find((l) => l.id === id);
}

export function nearestLocus(mx: number, my: number, maxDist: number): PlacedLocus | undefined {
  let best: PlacedLocus | undefined;
  let bestD = maxDist;
  for (const l of ATLAS) {
    const d = Math.hypot(l.mx - mx, l.my - my);
    if (d < bestD) {
      bestD = d;
      best = l;
    }
  }
  return best;
}
