export type Biome =
  | "cassia"
  | "yan"
  | "forbidden"
  | "barren"
  | "strange"
  | "jade"
  | "sand"
  | "sea"
  | "ore"
  | "foothill"
  | "shade"
  | "gorge"
  | "scree"
  | "quarry"
  | "crown"
  | "hollow"
  | "clearing"
  | "shelf";

export interface CanonMountain {
  id: string;
  name: string;
  x: number;
  z: number;
  peak: number;
  rx: number;
  rz: number;
  radius: number;
  biome: Biome;
  padX: number;
  padZ: number;
  quote: string;
  modern: string;
}

export const CANON: CanonMountain[] = [
  {
    id: "zhaoyao",
    name: "招搖之山",
    x: 0,
    z: 40,
    peak: 78,
    rx: 220,
    rz: 240,
    radius: 220,
    biome: "cassia",
    padX: -80,
    padZ: 36,
    quote: "其首曰招搖之山，臨於西海之上，多桂，多金玉。",
    modern: "南山首山，西臨大海，桂樹林立。",
  },
  {
    id: "yuanyi",
    name: "猨翼之山",
    x: 520,
    z: 20,
    peak: 92,
    rx: 90,
    rz: 220,
    radius: 90,
    biome: "forbidden",
    padX: 580,
    padZ: 8,
    quote: "又東三百八十里，曰猨翼之山，其中多怪獸，水多怪魚，多白玉，多腹虫，多怪蛇，多怪木，不可以上。",
    modern: "怪木怪蛇，山霧濃重，難以攀登。",
  },
  {
    id: "qingqiu",
    name: "青丘之山",
    x: 1040,
    z: 40,
    peak: 70,
    rx: 240,
    rz: 220,
    radius: 240,
    biome: "jade",
    padX: 1046,
    padZ: 12,
    quote: "又東三百里，曰青丘之山，其陽多玉，其陰多青雘。有獸焉，其狀如狐而九尾。",
    modern: "青雘之陰，九尾狐與灌灌鳥。",
  },
  {
    id: "danxue",
    name: "丹穴之山",
    x: 1560,
    z: -10,
    peak: 75,
    rx: 160,
    rz: 160,
    radius: 160,
    biome: "ore",
    padX: 1560,
    padZ: 50,
    quote: "又東五百里，曰丹穴之山，其上多金玉。丹水出焉，而南流注于渤海。",
    modern: "金玉之山，丹水南注，有鳳皇。",
  },
  {
    id: "ji-nanshan",
    name: "鷄山",
    x: 2080,
    z: 16,
    peak: 72,
    rx: 180,
    rz: 180,
    radius: 180,
    biome: "ore",
    padX: 2100,
    padZ: 40,
    quote: "又東五百里，曰鷄山，其上多金，其下多丹雘。黑水出焉，而南流注于海。",
    modern: "上金下丹雘，黑水南流。",
  },
  {
    id: "jingwei",
    name: "精衛灘",
    x: 2240,
    z: 480,
    peak: 10,
    rx: 220,
    rz: 160,
    radius: 220,
    biome: "sand",
    padX: 2240,
    padZ: 498,
    quote: "常銜西山之木石，以堙于東海。",
    modern: "東海未滿，木石三堆。",
  },
  {
    id: "zhurong",
    name: "祝融岬",
    x: 1560,
    z: 520,
    peak: 52,
    rx: 160,
    rz: 140,
    radius: 160,
    biome: "ore",
    padX: 1560,
    padZ: 548,
    quote: "南方祝融，獸身人面，乘兩龍。",
    modern: "丹穴以南火岬。",
  },
  {
    id: "hundun",
    name: "渾沌",
    x: -1080,
    z: 8,
    peak: 52,
    rx: 110,
    rz: 96,
    radius: 110,
    biome: "hollow",
    padX: -1080,
    padZ: 18,
    quote: "天地渾沌如雞子。有神焉，其狀如黃囊，赤如丹火，六足四翼，渾敦無面目，實惟帝江也。",
    modern: "卵殼窪地。帝江居其中。",
  },
  {
    id: "court",
    name: "顓頊廷丘",
    x: -1720,
    z: -340,
    peak: 52,
    rx: 160,
    rz: 120,
    radius: 160,
    biome: "crown",
    padX: -1720,
    padZ: -362,
    quote: "昔者共工與顓頊爭為帝。丘方圓三百里。竹南有赤澤水，名曰封淵。",
    modern: "北丘為廷。封淵與沈淵。",
  },
  {
    id: "buzhou",
    name: "不周主柱",
    x: -1680,
    z: 36,
    peak: 100,
    rx: 80,
    rz: 90,
    radius: 80,
    biome: "barren",
    padX: -1640,
    padZ: 72,
    quote: "有山而不合，名曰不周負子。怒而觸不周之山。天柱折，地維絕。",
    modern: "不合之柱。東南麓可上。",
  },
  {
    id: "kiln",
    name: "窑谷",
    x: -1440,
    z: 70,
    peak: 38,
    rx: 140,
    rz: 110,
    radius: 140,
    biome: "quarry",
    padX: -1432,
    padZ: 76,
    quote: "煉五色石以補蒼天，斷鰲足以立四極。",
    modern: "窑臺與四色石。第五空。",
  },
  {
    id: "xiayi",
    name: "下邑",
    x: -1260,
    z: 260,
    peak: 16,
    rx: 160,
    rz: 120,
    radius: 160,
    biome: "sand",
    padX: -1260,
    padZ: 260,
    quote: "地不滿東南，故水潦塵埃歸焉。",
    modern: "東南低地。柳與茅屋。",
  },
  {
    id: "kunlun-qiu",
    name: "崑崙之丘",
    x: -3120,
    z: -90,
    peak: 130,
    rx: 180,
    rz: 150,
    radius: 180,
    biome: "jade",
    padX: -3162,
    padZ: -82,
    quote: "崑崙之丘，是實惟帝之下都，神陸吾司之。黑水出焉，而西流於大杅。",
    modern: "陸吾與沙棠。四水出隅。",
  },
  {
    id: "kunlun-xu",
    name: "崑崙之墟",
    x: -2840,
    z: -380,
    peak: 150,
    rx: 200,
    rz: 170,
    radius: 200,
    biome: "crown",
    padX: -2840,
    padZ: -344,
    quote: "海內崑崙之墟，方八百里，高萬仞。面有九井，以玉為檻。面有九門。非仁羿莫能上岡之巖。",
    modern: "開明東嚮。南淵與弱水。",
  },
  {
    id: "yushan",
    name: "玉山",
    x: -2540,
    z: -660,
    peak: 110,
    rx: 160,
    rz: 140,
    radius: 160,
    biome: "ore",
    padX: -2530,
    padZ: -668,
    quote: "玉山，是西王母所居也。西王母其狀如人，豹尾虎齒而善嘯，蓬髮戴勝。",
    modern: "西王母之几。玉峯無林。",
  },
  {
    id: "changyang",
    name: "常羊之山",
    x: -1880,
    z: 380,
    peak: 48,
    rx: 160,
    rz: 140,
    radius: 160,
    biome: "barren",
    padX: -1880,
    padZ: 380,
    quote: "刑天與帝爭神，帝斷其首，葬之常羊之山，乃以乳為目，以臍為口，操干戚以舞。",
    modern: "刑天仍在此舞。無林木。",
  },
  {
    id: "kuafu",
    name: "夸父之路",
    x: 500,
    z: -940,
    peak: 28,
    rx: 280,
    rz: 220,
    radius: 280,
    biome: "foothill",
    padX: 80,
    padZ: -560,
    quote: "夸父與日逐走，入日。渴，欲得飲，飲於河渭；河渭不足，北飲大澤。棄其杖，化為鄧林。",
    modern: "河渭與鄧林。",
  },
  {
    id: "heichi",
    name: "黑齒岸",
    x: 3200,
    z: 90,
    peak: 28,
    rx: 200,
    rz: 140,
    radius: 200,
    biome: "barren",
    padX: 3080,
    padZ: 48,
    quote: "黑齒國在其北，為人黑，食稻啖蛇，一赤一青在其旁。",
    modern: "旱岸。羿營與月臺在此岸，不另傳。",
  },
  {
    id: "tanggu",
    name: "湯谷",
    x: 3520,
    z: 4,
    peak: 8,
    rx: 160,
    rz: 120,
    radius: 160,
    biome: "sand",
    padX: 3468,
    padZ: 4,
    quote: "湯谷上有扶桑，十日所浴，在黑齒北。居水中，有大木，九日居下枝，一日居上枝。",
    modern: "扶桑是木，不是山。",
  },
  {
    id: "ganyuan",
    name: "甘淵",
    x: 3780,
    z: 260,
    peak: 26,
    rx: 120,
    rz: 100,
    radius: 120,
    biome: "sand",
    padX: 3762,
    padZ: 282,
    quote: "有女子名曰羲和，方浴日于甘淵。羲和者，帝俊之妻，生十日。",
    modern: "十槽淺盆。常羲不在此。",
  },
  {
    id: "liubo",
    name: "流波山",
    x: 3960,
    z: -420,
    peak: 62,
    rx: 140,
    rz: 120,
    radius: 140,
    biome: "strange",
    padX: 3952,
    padZ: -420,
    quote: "東海中有流波山，入海七千里。其上有獸，狀如牛，蒼身而無角，一足，其名曰夔。",
    modern: "黃帝鼓在岸。",
  },
  {
    id: "fajiu",
    name: "發鳩之山",
    x: 420,
    z: -980,
    peak: 36,
    rx: 140,
    rz: 120,
    radius: 140,
    biome: "foothill",
    padX: 420,
    padZ: -980,
    quote: "又北二百里，曰發鳩之山，其上多柘木。有鳥焉，其狀如烏，文首、白喙、赤足，名曰精衛。",
    modern: "柘林。精衛舊巢。",
  },
];

export const TELEPORT_IDS = CANON.map((m) => m.id);

export function canonById(id: string): CanonMountain | undefined {
  return CANON.find((m) => m.id === id);
}
